// This file is auto-generated by `php artisan stimulus:install`
// Run that command whenever you add a new controller or create them with
// `php artisan stimulus:make controllerName`

import { Stimulus } from '../libs/stimulus'


import AdoptionApplicationController from './adoption-application_controller'
Stimulus.register('adoption-application', AdoptionApplicationController)

import DeleteModalController from './delete_modal_controller'
Stimulus.register('delete-modal', DeleteModalController)

import DonationModalController from './donation-modal_controller'
Stimulus.register('donation-modal', DonationModalController)

import FlashMessageController from './flash_message_controller'
Stimulus.register('flash-message', FlashMessageController)

import FormValidationController from './form-validation_controller'
Stimulus.register('form-validation', FormValidationController)

import ProfileReminderController from './profile-reminder_controller'
Stimulus.register('profile-reminder', ProfileReminderController)

import ReportSwitchController from './report_switch_controller'
Stimulus.register('report-switch', ReportSwitchController)

import RescueSwitchController from './rescue-switch_controller'
Stimulus.register('rescue-switch', RescueSwitchController)

import RescuesStatisticsController from './rescues_statistics_controller'
Stimulus.register('rescues-statistics', RescuesStatisticsController)

import SwitchSearchButtonController from './switch_search_button_controller'
Stimulus.register('switch-search-button', SwitchSearchButtonController)

import UpdateFoundReportController from './update-found-report_controller'
Stimulus.register('update-found-report', UpdateFoundReportController)

import UpdateLostReportController from './update-lost-report_controller'
Stimulus.register('update-lost-report', UpdateLostReportController)

import ViewReportModalController from './view_report_modal_controller'
Stimulus.register('view-report-modal', ViewReportModalController)

import WantToHelpBtnController from './want_to_help_btn_controller'
Stimulus.register('want-to-help-btn', WantToHelpBtnController)