// This file is auto-generated by `php artisan stimulus:install`
// Run that command whenever you add a new controller or create them with
// `php artisan stimulus:make controllerName`

import { Stimulus } from '../libs/stimulus'


import DeleteModalController from './delete_modal_controller'
Stimulus.register('delete-modal', DeleteModalController)

import FlashMessageController from './flash_message_controller'
Stimulus.register('flash-message', FlashMessageController)

import ReportSwitchController from './report_switch_controller'
Stimulus.register('report-switch', ReportSwitchController)

import RescueSwitchController from './rescue-switch_controller'
Stimulus.register('rescue-switch', RescueSwitchController)

import RescuesStatisticsController from './rescues_statistics_controller'
Stimulus.register('rescues-statistics', RescuesStatisticsController)

import SwitchSearchButtonController from './switch_search_button_controller'
Stimulus.register('switch-search-button', SwitchSearchButtonController)

import UpdateReportModalController from './update_report_modal_controller'
Stimulus.register('update-report-modal', UpdateReportModalController)

import ViewReportModalController from './view_report_modal_controller'
Stimulus.register('view-report-modal', ViewReportModalController)

import WantToHelpBtnController from './want_to_help_btn_controller'
Stimulus.register('want-to-help-btn', WantToHelpBtnController)