// This file is auto-generated by `php artisan stimulus:install`
// Run that command whenever you add a new controller or create them with
// `php artisan stimulus:make controllerName`

import { Stimulus } from '../libs/stimulus'


import ReportSwitchController from './report_switch_controller'
Stimulus.register('report-switch', ReportSwitchController)

import RescuesStatisticsController from './rescues_statistics_controller'
Stimulus.register('rescues-statistics', RescuesStatisticsController)

import SwitchSearchButtonController from './switch_search_button_controller'
Stimulus.register('switch-search-button', SwitchSearchButtonController)

import WantToHelpBtnController from './want_to_help_btn_controller'
Stimulus.register('want-to-help-btn', WantToHelpBtnController)